name: todo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  get_it: ^8.0.0
  flutter_riverpod: ^2.5.3
  dotted_border: ^2.1.0
  shared_preferences: ^2.3.2
  auto_size_text: ^3.0.0
  animated_reorderable_list: ^1.1.1
  riverpod_generator: ^2.6.2
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.3
  firebase_storage: ^12.3.6
  lottie: ^3.1.3
  dots_indicator: ^3.0.0
  build_runner: ^2.4.13
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/icons/
    - assets/images/
    


