// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-JW08LfKpRXYLz65q_rvaeY9wd1KNDxA',
    appId: '1:587681493162:android:b3af1e76983fc083fca0d3',
    messagingSenderId: '587681493162',
    projectId: 'todo-76167',
    storageBucket: 'todo-76167.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx2MBdNmep5iR0jIJLe1aimEos-OcXXuM',
    appId: '1:587681493162:ios:0b458f0ac85d291cfca0d3',
    messagingSenderId: '587681493162',
    projectId: 'todo-76167',
    storageBucket: 'todo-76167.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx2MBdNmep5iR0jIJLe1aimEos-OcXXuM',
    appId: '1:587681493162:ios:0b458f0ac85d291cfca0d3',
    messagingSenderId: '587681493162',
    projectId: 'todo-76167',
    storageBucket: 'todo-76167.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpF4w_rrhLEs4iBpPN-nsuEWt8Xb-NtOI',
    appId: '1:587681493162:web:44c57476d6814300fca0d3',
    messagingSenderId: '587681493162',
    projectId: 'todo-76167',
    authDomain: 'todo-76167.firebaseapp.com',
    storageBucket: 'todo-76167.firebasestorage.app',
    measurementId: 'G-6JQBSC97F8',
  );
}
